### ISSUE TITLE
Issue getting started

### ISSUE THREAD

**Issue by Tarang** [justengland/phantom-lambda-template#1]
Hi!

I've deployed this to lambda pretty much 'as is'. I ran a test and get this back:

```
{
  "errorMessage": "Process exited before completing request"
}
```

I have a generous timeout set, far more than the script runtime:

```
START RequestId: 12a34567-8121-12a1-2311-12345124a34a
2015-05-17T07:51:09.422Z    12a34567-8121-12a1-2311-12345124a34a    Calling phantom:  /var/task/node_modules/phantomjs/bin/phantomjs [ '/var/task/phantomjs-script.js' ]
Process exited before completing request

END RequestId: 12a34567-8121-12a1-2311-12345124a34a
REPORT RequestId: 12a34567-8121-12a1-2311-12345124a34a  Duration: 343.36 ms Billed Duration: 400 ms     Memory Size: 128 MB Max Memory Used: 9 MB   
```

Is this anything you've experienced? I was expecting to get back `Hello from phantomjs` instead.

**Comment by justengland** [comment]
Sorry about the slow response. The issues I have seen have mostly been around deploying phantomjs.  What system are you developing with? mac, windows, linux

**Comment by Tarang** [comment]
I found the issue this path https://github.com/justengland/phantom-lambda-template/blob/master/index.js#L13 should include phantomjs too not just node_modules.

This is in case `npm install` is used (as it always is) but phantomjs is installed just not via node

**Comment by justengland** [comment]
The issue with npm is interesting, npm does not work very well for phantomjs w/ lambda because lambda runs on a different machine that most dev machines and phantom is not just javascript. I have been thinking about this issue for while and the best way to handle it. 

My original idea was just include the copy of the aws-linux version of phantom, so I don't have to do an npm install as a part of my lambda function because I did not want to install. I would like to improve this operation.

**Comment by Tarang** [comment]
Its fine with the way you've put it. Just your check for phantomjs doesn't check for phantomjs it checks for `node_modules` which will inevitably be installed if the script is to run locally [not on the aws lambda environment](whether or not phantomjs is installed).

So if someone has `phantomjs` installed via brew or from source it wouldn't work. If the module is installed via npm it would have `node_modules/phantomjs` which would then be the cue to use that path as the correct phantomjs path over the one in $PATH (typically /usr/bin/phantomjs)

**Comment by justengland** [comment]
Would you like to submit a pull request?

**Comment by christianklotz** [comment]
I [forked](https://github.com/christianklotz/phantom-lambda-template) the template, updating it to use the latest version of node-lambda and made a few other amendments. This allowed to remove the package.sh and relying on the `node-lambda deploy` command. There's one catch though – I had to address an issue with the zip-creation in `node-lambda` which caused the binary to have the wrong file permissions. See the [README](https://github.com/christianklotz/phantom-lambda-template/blob/master/README.md) for more.

Also by moving the `phantomjs` to `devDependencies` it will correctly install it on the development machine and exclude it on Amazon Lambda so it uses the included `phantomjs` binary built for AWS Linux.

**Comment by justengland** [comment]
@christianklotz simplifies this integration, please give it a try and let me know. For now I am closing the bug.

**Comment by orRosenthal** [comment]
Hey, I have a similar issue. Deployed the lambda function as is, but getting timeout when executing with the following error:

2016-12-26T09:47:35.817Z	53b08c40-cb50-11e6-90d7-a7ab50a1bfdb	Pahntom js path is: /var/task/node_modules/phantomjs-prebuilt/bin/phantomjs
2016-12-26T09:47:35.818Z	53b08c40-cb50-11e6-90d7-a7ab50a1bfdb	Calling phantom:  path: /var/task/node_modules/phantomjs-prebuilt/bin/phantomjs, args: /var/task/phantomjs-script.js
2016-12-26T09:47:36.998Z	53b08c40-cb50-11e6-90d7-a7ab50a1bfdb	phantom error :  Error executing phantom at /usr/local/bin/phantomjs

I run the function locally (osx) and it worked. 
Do you have an idea what's i'm doing wrong?
Thanks.
