### ISSUE TITLE
AWS permissions

### ISSUE THREAD

**Issue by tf42src** [justengland/phantom-lambda-template#13]
Could you attach your IAM permissions for simple copy and paste? That would be great!

**Comment by justengland** [comment]
I use a pretty basic permissions in this example, but I can certainly give you a more complicated example. Using the basic permissions that come out of the box.

Here is an example I have used before, its not published, but feel free to use it as a sample.

---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Transform: AWS::Serverless-2016-10-31
Description: Cloudformation Entrypoint for the API and Services section of the project

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      DefinitionBody:
        # SWAGGER START - there is no variable substitution if its not in the CFN Template.
        swagger: 2.0
        info:
          title: !Ref AWS::StackName
          description: "The api gateway used for build handlers"
        schemes:
            - "https"
        paths:
          /:
            get:
              consumes:
              - "application/json"
              produces:
              - "application/json"
              responses:
                '200':
                  description: The home of the API.
                  schema:
                    $ref: "#/definitions/Empty"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                passthroughBehavior: "when_no_match"
                type: "mock"
          /v1_0/bitbucket:
            get:
              produces:
              - "application/json"
              responses:
                '200':
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${BitbucketWebhookHandler}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws_proxy"
            post:
              produces:
              - "application/json"
              responses:
                '200':
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${BitbucketWebhookHandler}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws_proxy"
        definitions:
          Empty:
            type: "object"
            title: "Empty Schema"

  LambdaApiGatewayExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt BitbucketWebhookHandler.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - !Ref Api
          - '/*/*'

  DefaultLambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
          Path: /
          RoleName: !Join [ '-', [ !Ref 'AWS::StackName', 'default-lambda' ] ]
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  AWS: arn:aws:iam::674173784229:root
                Action: sts:AssumeRole
              - Effect: Allow
                Principal:
                  Service:
                  - lambda.amazonaws.com
                Action: sts:AssumeRole
          Policies:
            - PolicyName:  !Join [ '-', [ !Ref 'AWS::StackName', 'default-lambda' ] ]
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Action:
                  - logs:*
                  - lambda:*
                  - codebuild:StartBuild
                  - cloudfront:*
                  - codepipeline:*
                  - sns:*
                  - s3:*
                  - sts:*
                  - execute-api:Invoke
                  - iam:PassRole
                  - iam:GetRole
                  - iam:GetUser
                  - iam:CreateRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:DeleteRole
                  - iam:AttachRolePolicy
                  - iam:UpdateAssumeRolePolicy
                  - iam:DetachRolePolicy
                  "Resource": "*"

  # Lambda Functions
  BitbucketWebhookHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bit-bucket-webhook.handler
      MemorySize: 256
      Role: !GetAtt DefaultLambdaExecutionRole.Arn
      Runtime: nodejs6.10
      Timeout: 60
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /v1_0/bitbucket
            Method: GET
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY

  CrossAccountCFNExecution:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: deploy-v1-hotspare-to-prod.handler
      MemorySize: 256
      Role: !GetAtt DefaultLambdaExecutionRole.Arn
      Runtime: nodejs6.10
      Timeout: 300
      Environment:
        Variables:
          STACK_NAME: "production-v2"
          TIMEOUT_COUNT: "10"
          LAMBDA_TIMEOUT_OFFSET: "2001"

  BitbucketToAWSCodeExecution:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: pipeline-to-build.handler
      MemorySize: 256
      Role: !GetAtt DefaultLambdaExecutionRole.Arn
      Runtime: nodejs6.10
      Timeout: 300
      Environment:
        Variables:
          STACK_NAME: "production-v2"
          TIMEOUT_COUNT: "10"
          LAMBDA_TIMEOUT_OFFSET: "1001"

Outputs:
  ApiConsoleUrl:
    Description: Console URL for the API Gateway API's Stage.
    Value: !Join
      - ''
      - - https://
        - !Ref 'AWS::Region'
        - '.console.aws.amazon.com/apigateway/home?region='
        - !Ref 'AWS::Region'
        - '#/apis/'
        - !Ref Api
        - '/stages/prod'

  ApiUrl:
    Description: Invoke URL for your API. Clicking this link will perform a GET request
      on the root resource of your API.
    Value: !Join
      - ''
      - - https://
        - !Ref Api
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/prod'

  ApiId:
    Description: API Gateway API ID.
    Value: !Ref Api
